### ISSUE TITLE
ridge regression algorithm code error

### ISSUE THREAD

**Issue by JoeanAmier** [PacktPublishing/Machine-Learning-for-OpenCV-Second-Edition#2]
/Chapter03/03.04-Applying-Lasso-and-Ridge-Regression.ipynb
error:
"""
For the ridge regression algorithm, we would change the preceding line of code to the following:
In [19]: ridgereg = linear_model.RidgeRegression()
"""
should be:
"""
In [19]: ridgereg = linear_model.Ridge()
"""

**Comment by vishwesh5** [comment]
Hi, I have fixed the same. Thanks for bringing it to our notice.
